# Generated by Django 4.1.7 on 2023-02-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_username_newuser_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
